name: test

on:
  pull_request:
    branches:
      - main

jobs:
  run-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "16"

      - name: lint
        run: npm run lint

      - name: TEST
        run: npm run test
